### ISSUE TITLE
poi

### ISSUE THREAD

**Issue by huanleifengbao** [syj2010syj/All-Star-Battle-2#113]
夏娜Q暴击应该是+1倍而不是默认2倍
缺少设定：如果攻击伤害已经击杀目标，Q的暴击就不会触发

**Comment by syj2010syj** [comment]
e75e9b19f60e0521da0823d3a86fc4a9a8f51cc6

早修正了

**Comment by huanleifengbao** [comment]
我次奥 原来你记得！
那再加一个！被防偷塔和250抗性所减免的伤害，在计算额外护甲时不增加护甲

**Comment by syj2010syj** [comment]
4040e53a2ee969e2edd902ea962457465a8cd84c
