### ISSUE TITLE
免疫致死伤害的优先级问题

### ISSUE THREAD

**Issue by liehun10086** [syj2010syj/All-Star-Battle-2#77]
本来不该存在这个优先级的
但是小爱R也免疫致死伤害，且和其他免疫致死伤害的技能同时触发，意思就是说即使免疫了致死伤害，但是还是要触发小爱R的效果，造成击杀者定身和目标英雄持续战斗5s并在5s后死去

**Comment by syj2010syj** [comment]
已完成
